name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: " Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "documentation"
      - "docs"
      - "refactor"
      - "test"
      - "ci"
      - "perf"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "feat"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "hotfix"
      - "docs"
      - "documentation"
      - "chore"
  default: patch

autolabeler:
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
      - "/bug/i"
  - label: "feature"
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - "/feat/i"
      - "/feature/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"
  - label: "documentation"
    branch:
      - '/docs?\/.+/'
    title:
      - "/docs/i"
      - "/documentation/i"
    files:
      - "*.md"
      - "docs/**/*"
  - label: "refactor"
    branch:
      - '/refactor\/.+/'
    title:
      - "/refactor/i"

template: |
  ## What's Changed in $NEXT_PATCH_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Installation

  [Setup](https://github.com/Mynster9361/AzureAutomationSourceControl?tab=readme-ov-file#setup) For step by step instructions.

  ```yaml
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Important to fetch all history for proper diffs

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Sync Azure Automation Runbooks
      uses: $OWNER/$REPOSITORY@v$RESOLVED_VERSION
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        automationAccountName: ${{ secrets.AUTOMATION_ACCOUNT_NAME }}
        path: './runbooks'

  ```

  ## Contributors

  $CONTRIBUTORS


  ## Full documentation

  See the [README](https://github.com/Mynster9361/AzureAutomationSourceControl/blob/main/README.md) for full documentation.
