name: Sync Azure Automation Runbooks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-runbooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Important to fetch all history for proper diffs

    - name: Get changed files
      id: changed-files
      run: |
        # Different approach based on event type
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          # For pull requests, compare base and head commits
          echo "Getting changes from PR"
          DIFF_OUTPUT=$(git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          # For pushes, compare previous and current commits
          echo "Getting changes from push"
          if [[ -n "${{ github.event.before }}" && "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
            DIFF_OUTPUT=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }})
          else
            # First push to branch case - compare with the first parent commit
            echo "First push to branch, getting all files"
            DIFF_OUTPUT=$(git diff --name-status $(git rev-parse HEAD^) ${{ github.sha }})
          fi
        else
          # For workflow_dispatch or other events, list all files
          echo "Manual workflow run, getting all files"
          DIFF_OUTPUT=$(find . -type f -not -path "*/\.*" -not -path "*/node_modules/*" | sed 's/^\.\//A /')
        fi
        echo "$DIFF_OUTPUT"

        # Separate added/modified and deleted files
        ADDED_MODIFIED_FILES=$(echo "$DIFF_OUTPUT" | grep -E '^(A|M)\s' | awk '{print $2}' | tr '\n' ' ')
        DELETED_FILES=$(echo "$DIFF_OUTPUT" | grep -E '^D\s' | awk '{print $2}' | tr '\n' ' ')
        echo "ADDED_MODIFIED_FILES=$ADDED_MODIFIED_FILES" >> $GITHUB_ENV
        echo "DELETED_FILES=$DELETED_FILES" >> $GITHUB_ENV

    - name: Display changed files
      run: |
        echo "Added or Modified files:"
        echo "$ADDED_MODIFIED_FILES"
        echo "----------------------"
        echo "Deleted files:"
        echo "$DELETED_FILES"

    # Here you would add the Azure login and runbook sync steps
    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Sync Azure Automation Runbooks
    #   uses: ./  # Assumes the action is in the root of this repository
    #   with:
    #     subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     resource_group: ${{ secrets.RESOURCE_GROUP_NAME }}
    #     automation_account: ${{ secrets.AUTOMATION_ACCOUNT_NAME }}
    #     runbooks_path: "."  # Or your specific path
    #     sync_mode: "Changed"  # Only process changed files
    #     delete_mode: "OnlyDeleted"  # Only delete files explicitly removed