name: Sync Azure Automation Runbooks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      path_filter:
        description: 'Path filter to process (e.g., "runbooks/" for specific folder, "." for all files)'
        required: false
        default: '.'
      recursive:
        description: 'Process files recursively within the path_filter directory'
        required: false
        type: boolean
        default: true
      exclude_paths:
        description: 'Comma-separated list of paths to exclude (e.g., ".github/,.vscode/")'
        required: false
        default: '.github/,.vscode/,docs/,README.md,LICENSE'
      validate_all:
        description: 'Process all files rather than just changed ones'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  sync-runbooks:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Important to fetch all history for proper diffs

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: Mynster9361/AzureAutomationSourceControl@main
      with:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        automation_account: ${{ secrets.AZURE_AUTOMATION_ACCOUNT }}
        path_filter: ${{ github.event.inputs.path_filter || '.' }}
        recursive: ${{ github.event.inputs.recursive || 'true' }}
        exclude_paths: ${{ github.event.inputs.exclude_paths || '.github/,.vscode/,docs/,README.md,LICENSE' }}
        validate_all: ${{ github.event.inputs.validate_all || 'false' }}